### ISSUE TITLE
The abuse filter data syntax has changed

### ISSUE THREAD

**Issue by 5j9** [he7d3r/mw-gadget-AbuseFilterExecutionStats#1]
Thanks for the script. But it seems that [the time and condition consumption data are omitted.](https://translatewiki.net/w/i.php?title=MediaWiki:Abusefilter-edit-status/en&diff=6184754&oldid=3378620)

Currently the script creates an empty table for me.

**Comment by he7d3r** [comment]
Unfortunately, there is nothing we can do on client side (e.g. on this script), as those statistics were removed from AbuseFilter extension:
https://gerrit.wikimedia.org/r/#/c/211951/
https://phabricator.wikimedia.org/T101648
